name: tidebot-webui

services:
  tidebot-open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: tidebot-open-webui:local
    container_name: tidebot-open-webui
    volumes:
      - tidebot-open-webui:/app/backend/data
    ports:
      - ${TIDEBOT_OPEN_WEBUI_PORT-3001}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_BASE_URLS=https://api.minimax.io/v1
      - OPENAI_API_KEYS=${MINIMAX_API_KEY}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - open-webui
    restart: unless-stopped

volumes:
  tidebot-open-webui: {}

networks:
  open-webui:
    external: true
    name: open-webui_default
